DROP TABLE IF EXISTS go_mods;
CREATE TABLE IF NOT EXISTS go_mods (id INTEGER PRIMARY KEY, slug VARCHAR(12) NOT NULL UNIQUE, branch VARCHAR(16) default "main" NOT NULL, import_url TEXT NOT NULL, repo_url TEXT NOT NULL);
