name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - dev
    paths:
      - .github/workflows/deoply.yml
      - tsconfig.json
      - package.json
      - wrangler.jsonc
      - src/**
      - pages/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        if: secrets.CLOUDFLARE_API_TOKEN != "disable"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.7.0"
          command: |
            deploy
            pages deploy pages --project-name gomods
